// Usage: node --env-file-if-exists=.env.local scripts/db.mts <migrate|seed|reseed|sql>
//   migrate  apply supabase/migrations/*.sql and seed an empty database
//   reseed   re-insert the catalog seed (destinations, FAQs, reviews, events, holidays)
//   sql      write supabase/seed.sql for use in the Supabase SQL editor
import { writeFile } from "node:fs/promises";
import { getDb, migrate, seed } from "../src/lib/db/core.ts";

const cmd = process.argv[2] ?? "migrate";
const db = await getDb();
console.log(`database: ${db.kind}`);

if (cmd === "migrate") {
  await migrate(db, console.log);
  await seed(db, { log: console.log });
} else if (cmd === "seed" || cmd === "reseed") {
  await seed(db, { force: cmd === "reseed", log: console.log });
} else if (cmd === "sql") {
  const tables = ["destinations", "faqs", "reviews", "events", "holidays", "fee_changes"];
  let out = "-- Generated by `npm run db:seed-sql`. Run after the migrations in the Supabase SQL editor.\n";
  for (const t of tables) {
    const rows = await db.query<{ line: string }>(
      `select format('insert into %I select * from jsonb_populate_record(null::%I, %L::jsonb) on conflict do nothing;', '${t}', '${t}', to_jsonb(x)) as line from ${t} x`,
    );
    out += rows.map((r) => r.line).join("\n") + "\n";
  }
  await writeFile("supabase/seed.sql", out);
  console.log("wrote supabase/seed.sql");
} else {
  console.error(`unknown command ${cmd}`);
  process.exit(1);
}
process.exit(0);
